### PR TITLE
Confirmation and Fixes

### PR DESCRIPTION
**Pull request by hasib-rashid**
@SpiderMath hey there. Would be very happy if you would look at the type definitions of the confirmation.ts file.

<3

### CODE REVIEW

**Comment by hasib-rashid** [comment]
Hey there. Added some more features. Waiting for merge 😅. No rush. pls check everything if its okay

**Review by SpiderMath — CHANGES_REQUESTED** [review]
Is it possible to keep it package-lock.json?
Since changing package-lock.json -> yarn.lock changes the consistency. :thinking: 
Also, keeping .vscode is my habit, it isn't being published as yk, so can we not remove that :sweat_smile:

**Comment by SpiderMath** [comment]
Also, about the Export, the Examples have been fixed & there was no need for the default export, since it exports the object already. It could be imported as
```js
const Multipurpose = require("discord-multipurpose");
console.log(Multipurpose.Image)
// Logs the Image class
```

**Comment by SpiderMath** [comment]
And I'd also requested to make Discord.js a peer Dependency, not a direct dependency :no_mouth:

**Comment by hasib-rashid** [comment]
Just saying that if this package booms then there is a really high chance that other people will contribute to this project. And people have their own custom theme and doesnt use the default theme as the given one in the settings.json

**Comment by hasib-rashid** [comment]
**~~I may or may not know what a peer dependency is...... My first time contributing to a npm package 😅~~**

Please make the changes so that i can kinda see what this is. (Out of context)

**Comment by SpiderMath** [comment]
Hmm, I understand.
You're right about the config thingy, but could you just replace yarn.lock with package-lock.json? Since that is quite a bit of a large jump.
I'll be removing .vscode shortly :thinking: 

Also for peerDependencies, I'll do that myself soon :tm:

**Comment by hasib-rashid** [comment]
Yeah you can .gitignore that. I wanted to gitignore both of them but my vscode editor didnt seem to ignore them.

I don't know why. Pls do the changes since I cant be sure if those are ignored or not. :/

**Review by SpiderMath — APPROVED** [review]

**Comment by hasib-rashid** [comment]
I think you can merge the code now. I am about to add a new feature

**Comment by hasib-rashid** [comment]
Ah yes this branch thing isnt fixing. Please merge the #4

**Pull request closed without merging**
